# Generated by Django 5.1.7 on 2025-04-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_especialidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['nome'], 'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
    ]
