# Generated by Django 5.1.7 on 2025-04-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_especialidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidade',
            options={},
        ),
    ]
