# Generated by Django 5.1.7 on 2025-03-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='agendada', max_length=20)),
            ],
        ),
    ]
