# Generated by Django 5.1.7 on 2025-04-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_cidade_usuario_estado_usuario_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='longitude',
        ),
    ]
